import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  const router = useRouter();
  const isActive: (pathname: string) => boolean = (pathname) => {
    return router.pathname === pathname;
  };
  const { data: session, status } = useSession();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the AI Tutor! Please sign</h1>
      {status === "loading" && <div>Loading...</div>}
      {status === "unauthenticated" && (
        <div>
          <Link href="/api/auth/signin">Sign in</Link>
        </div>
      )}
      {status === "authenticated" && (
        <div>
          <p>Hi {session.user?.name}!</p>
          <Link href="/interface">Go to Interface</Link>
          <br />
          <button onClick={() => signOut()}>Sign out</button>
        </div>
      )}
    </>
  );
}
