import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen py-2">
        <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
          <h1 className="text-6xl font-bold">two_sd</h1>
          <p className="mt-3 text-2xl">AI Tutors That Work</p>
          <div className="flex flex-wrap items-center justify-around max-w-4xl mt-6 sm:w-full">
            <Link
              href="/interface"
              className="p-6 mt-6 text-left border w-96 rounded-xl hover:text-gray-600 focus:text-gray-600"
            >
              <h3 className="text-2xl font-bold">Tutor &rarr;</h3>
              <p className="mt-4 text-xl">
                Jump right in and start your first session
              </p>
            </Link>
            <Link
              href="/about"
              className="p-6 mt-6 text-left border w-96 rounded-xl hover:text-gray-600 focus:text-gray-600"
            >
              <h3 className="text-2xl font-bold">Guide &rarr;</h3>
              <p className="mt-4 text-xl">
                Learn more about how to get the most out of our AI tutors
              </p>
            </Link>
          </div>
        </main>
      </div>
    </Layout>
  );
}
