import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [test, setTest] = useState("");
  const router = useRouter();
  const isActive: (pathname: string) => boolean = (pathname) => {
    return router.pathname === pathname;
  };
  const { data: session, status } = useSession();
  const testPrompt = async () => {
    const res = await fetch("/api/prompt", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ subject: "Biology" }),
    });
    const data = await res.json();
    setTest(data.result);
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the AI Tutor! Please sign</h1>
      {status === "loading" && <div>Loading...</div>}
      {status === "unauthenticated" && (
        <div>
          <Link href="/api/auth/signin">Sign in</Link>
        </div>
      )}
      {status === "authenticated" && (
        <div>
          <p>Hi {session.user?.name}!</p>
          <Link href="/interface">Go to Interface</Link>
          <br />
          <button onClick={() => signOut()}>Sign out</button>
        </div>
      )}
      <br />
      <button
        onClick={testPrompt}
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      >
        Test Prompt
      </button>
      <p>{test}</p>
    </>
  );
}
